NationalPark.create(name: "Yellowstone",
                    description: "Yellowstone National Park is a nearly" \
                    "3,500-sq.-mile wilderness" \
                    "recreation area atop a volcanic hot spot." \
                    "Mostly in Wyoming, the park spreads into parts of Montana and Idaho too." \
                    "Yellowstone features dramatic canyons, alpine rivers, lush forests, hot springs and" \
                    "gushing geysers, including its most famous, Old Faithful." \
                    "It's also home to hundreds of animal species, including bears, wolves, bison, elk and antelope.",
                    image_url: "https://koa.com/blog/images/secrets-of-yellowstone-np.jpg?preset=blogPhoto")

NationalPark.create(name: "Grand Teton",
                    description: "It’s time to meet one of Wyoming’s most" \
                    "stunning destinations—Grand Teton National Park." \
                    "Located south of Yellowstone National Park and north of the town of Jackson," \
                    "Grand Teton’s 310,000 acres includes lush valley floors, mountain meadows," \
                    "alpine lakes and the rising peaks of the Teton Range." \
                    "While iconic locations like Mormon Row and the Moulton Barns may be the most" \
                    "photographed destinations in the park, Grand Teton’s celestial peaks also provide" \
                    "the perfect setting for nature lovers, outdoor adventurers and road trippers who are" \
                    "looking to explore the park’s incredible landscapes.",
                    image_url: "https://www.gannett-cdn.com/presto/2020/02/25/USAT/f35575e4-40c2-43b3-a698-2dddd05528bb-GettyImages-108328668.jpg?width=2560") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Great Smoky Mountains",
                    description: "Ridge upon ridge of forest straddles the border" \
                    "between North Carolina and Tennessee in Great Smoky Mountains National Park." \
                    "World renowned for its diversity of plant and animal life, the beauty of its ancient mountains," \
                    "and the quality of its remnants of Southern Appalachian mountain culture," \
                    "this is America's most visited national park.",
                    image_url: "https://www.randmcnally.com/images/blog/_500/Great-Smoky-Mountains-National-Park_500x300.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Carlsbad Caverns", description: "Carlsbad Caverns National Park in New Mexico contains some of the largest caves in North America—a must-visit stop for vacations in New Mexico. As you pass through the Chihuahuan Desert and Guadalupe Mountains of southeastern New Mexico and west Texas, filled with prickly pear, chollas, sotols, and agaves, you might never guess there are more than 300 known caves beneath the surface. The park contains 113 of these caves, formed when sulfuric acid dissolved the surrounding limestone. This includes Lechuguilla Cave, the nation's deepest and fourth longest limestone cave at 1,567 feet (478m).", image_url: "https://newmexiconewsport.com/wp-content/uploads/2015/02/USA_carlsbad_caverns1_NM-1536x1152.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Black Canyon Of The Gunnison", description: "Black Canyon of the Gunnison National Park is in western Colorado. It surrounds part of a deep, steep-walled gorge carved through Precambrian rock by the Gunnison River. Roads and trails along the north and south rims have views of the Black Canyon's dramatic drops and the striated Painted Wall cliff. The winding East Portal Road descends to the river. Wildlife includes mule deer, elk and golden eagles.", image_url: "https://nas-national-prod.s3.amazonaws.com/styles/hero_image/s3/black-canyon-of-the-gunnison.jpg?itok=C3GYNZow") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Great Sand Dunes", description: "A sandbox of epic proportions, the entire dune field encompasses 30 square miles and the tallest dune towers 750 feet high. The kid in every visitor loves to sled down the sand year-round and plunge into the soft-sand tracks of those who climbed ahead of them. Aside from the dunes, you'll find picnicking, hiking and camping opportunities, the challenging four-wheel scenic drive on Medano Pass, horseback-riding trails, the mysteriously appearing and disappearing Medano Creek, ranger-led nature walks and a couple of 14,000- and 13,000-foot peaks to climb.", image_url: "https://www.alamosa.org/images/alamosa/yrdm23ayq2kiibvpdslc.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Zion", description: "Zion National Park is a southwest Utah nature preserve distinguished by Zion Canyon’s steep red cliffs. Zion Canyon Scenic Drive cuts through its main section, leading to forest trails along the Virgin River. The river flows to the Emerald Pools, which have waterfalls and a hanging garden. Also along the river, partly through deep chasms, is Zion Narrows wading hike.", image_url: "https://www.jetsetter.com/uploads/sites/7/2018/04/gfMXx2gQ.jpeg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Arches", description: "Arches National Park lies north of Moab in the state of Utah. Bordered by the Colorado River in the southeast, it’s known as the site of more than 2,000 natural sandstone arches, such as the massive, red-hued Delicate Arch in the east. Long, thin Landscape Arch stands in Devils Garden to the north. Other geological formations include Balanced Rock, towering over the desert landscape in the middle of the park.", image_url: "https://npca.s3.amazonaws.com/images/8566/5a7c0399-3d5b-455e-97cd-40ca4bdb8296-banner.jpg?1445969608") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Canyonlands", description: "Canyonlands National Park in southeastern Utah is known for its dramatic desert landscape carved by the Colorado River. Island in the Sky is a huge, flat-topped mesa with panoramic overlooks. Other notable areas include the towering rock pinnacles known as the Needles, the remote canyons of the Maze and the Native American rock paintings in Horseshoe Canyon. Whitewater rapids flow through Cataract Canyon.", image_url: "https://www.discovermoab.com/wp-content/uploads/2017/06/canyonlands_main_image.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Bryce Canyon", description: "Bryce Canyon National Park, a sprawling reserve in southern Utah, is known for crimson-colored hoodoos, which are spire-shaped rock formations. The park’s main road leads past the expansive Bryce Amphitheater, a hoodoo-filled depression lying below the Rim Trail hiking path. It has overlooks at Sunrise Point, Sunset Point, Inspiration Point and Bryce Point. Prime viewing times are around sunup and sundown.", image_url: "https://s27363.pcdn.co/wp-content/uploads/2017/08/Thors-Hammer-Bryce.jpg.optimal.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Capitol Reef", description: "Capitol Reef National Park is in Utah's south-central desert. It surrounds a long wrinkle in the earth known as the Waterpocket Fold, with layers of golden sandstone, canyons and striking rock formations. Among the park's sights are the Chimney Rock pillar, the Hickman Bridge arch, and Capitol Reef, known for its white sandstone domes. In the north are the towering monoliths of Cathedral Valley.", image_url: "https://capitolreef.org/wp-content/uploads/2017/10/Home_Main.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Grand Canyon", description: "Grand Canyon National Park, in Arizona, is home to much of the immense Grand Canyon, with its layered bands of red rock revealing millions of years of geological history. Viewpoints include Mather Point, Yavapai Observation Station and architect Mary Colter’s Lookout Studio and her Desert View Watchtower. Lipan Point, with wide views of the canyon and Colorado River, is a popular, especially at sunrise and sunset.", image_url: "https://www.tripsavvy.com/thmb/KyPHyyx2O9y2ZOSeNNl5qdPRqJ4=/2119x1415/filters:fill(auto,1)/GrandCanyonNationalPark-d97b78edfff14d52bca71f5962ac2af5.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Yosemite", description: "Yosemite National Park is in California’s Sierra Nevada mountains. It’s famed for its giant, ancient sequoia trees, and for Tunnel View, the iconic vista of towering Bridalveil Fall and the granite cliffs of El Capitan and Half Dome. In Yosemite Village are shops, restaurants, lodging, the Yosemite Museum and the Ansel Adams Gallery, with prints of the photographer’s renowned black-and-white landscapes of the area.", image_url: "https://cdn.vox-cdn.com/thumbor/lObMEqryzjVUW4TBQrzw-rqVNeY=/0x0:1023x682/1400x1050/filters:focal(0x0:1023x682):format(jpeg)/cdn.vox-cdn.com/uploads/chorus_image/image/32525883/9385444742_02ac1f9581_b.0.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Crater Lake ", description: "Crater Lake National Park is in the Cascade Mountains of southern Oregon. It’s known for its namesake Crater Lake, formed by the now-collapsed volcano, Mount Mazama. Wizard Island is a cinder cone near the western edge of the lake. The Rim Drive, a road surrounding the lake, offers views of the park’s volcanic formations. The park’s numerous trails include Sun Notch, with views of the Phantom Ship, a small island.", image_url: "https://media-cdn.tripadvisor.com/media/photo-s/0d/be/eb/e6/wizard-island.jpg") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Craters Of The Moon", description: "The monument preserves around 53,500 acres of volcanic formations and lava flows on the northern rim of the Snake River Plain in southcentral Idaho. A desolate yet sublime landscape that could only be described as weird, the monument has never failed to inspire, if not evoke ambivalent responses from even its most ardent supporters left speechless by the unusual lava terrain.", image_url: "https://images.squarespace-cdn.com/content/v1/5a87961cbe42d637c54cab93/1580376085748-W16OCLK8RTMOCI65FQAW/ke17ZwdGBToddI8pDm48kNCH0IFo-E28D0rm_d_wnF4UqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKczdH3qUBwO6oWXP_OkYMa5KbLFw5Om5Yp_Nt25Y6nc5ZZuUUY1FOqARMqv9i1pcqr/craters-of-the-moon-idaho.jpg?format=1500w") # rubocop:disable Layout/LineLength

NationalPark.create(name: "Badlands", description: "Badlands National Park is in South Dakota. Its dramatic landscapes span layered rock formations, steep canyons and towering spires. Bison, bighorn sheep and prairie dogs inhabit its sprawling grasslands. The Badlands Loop Road (Highway 240) winds past scenic lookouts. Several trails begin near the Ben Reifel Visitor Center. The Fossil Exhibit Trail is a boardwalk with displays on fossils uncovered in the park.", image_url: "https://www.doi.gov/sites/doi.gov/files/uploads/badlands-np-andreas-eckert-ste-small_1.jpg") # rubocop:disable Layout/LineLength
